(defun print-board (board)
  (format t "~&~S | ~S | ~S~%" (first board)
          (second board)
          (third board))
  (format t "--------------~%")
  (format t "~S | ~S | ~S~%" (fourth board)
          (fifth board)
          (sixth board))
  (format t "--------------~%")
  (format t "~S | ~S | ~S~%" (seventh board)
          (eighth board)
          (ninth board)))

(print-board '(x o o nil x nil o nil x))
